#THIS FILE WAS GENERATED WITH THE "docker init" COMMAND.
# By answering simple questions, it autogenerated this dockerfile, .dockerignore, and compose.yaml
# It was modified with the help of VSCode's built in Copilot AI 🙏
# Mainly due to the fact that I was running into permission issues with package-lock.json

# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG NODE_VERSION=25.0.0

FROM node:${NODE_VERSION}-alpine

# Use production node environment by default.
# Added API specific environment variables.
ENV NODE_ENV development

ENV DB_HOST host.docker.internal

WORKDIR /usr/src/app

# Copy package files first.
COPY package.json package-lock.json ./

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
RUN --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

# Copy the rest of the source files into the image.
COPY . .

# Ensure all files are owned by the node user so they can read/write.
RUN chown -R node:node /usr/src/app

# Run the application as a non-root user.
USER node

# Expose the port that the application listens on.
EXPOSE 7156

# Run the application.
CMD npm start
