{
 "title": "Metrics Collection Up",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "up", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "In-Use Heap Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "api_nodejs_heap_size_used_bytes",
     "legendFormat": "{{group}}"
    },
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "{{group}}" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Connected Services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_nodejs_version_info", "legendFormat": "{{instance}}" },
    { "expr": "nodejs_version_info", "legendFormat": "{{instance}}" },
    { "expr": "go_info", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "api_process_cpu_seconds_total", "legendFormat": "{{group}}" },
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Change in CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(api_process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{group}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}